name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Mkdir
        run: mkdir ./build

      - name: make
        run: g++ -o ./build/run ./PyLFMF/*.cpp
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./build
  job2:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Mkdir
        run: mkdir ./build

      - name: make
        run: g++ -o ./build/run.exe ./PyLFMF/*.cpp
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./build
  job3:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Mkdir
        run: mkdir ./build

      - name: make
        run: g++ -o ./build/run.exe ./PyLFMF/*.cpp
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./build
